# Generated by Django 2.0.2 on 2018-05-09 19:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_device'),
    ]

    operations = [
        migrations.AddField(
            model_name='device',
            name='latitude',
            field=models.FloatField(blank=True, null=True, verbose_name='纬度'),
        ),
        migrations.AddField(
            model_name='device',
            name='location',
            field=models.CharField(blank=True, max_length=64, null=True, verbose_name='地点'),
        ),
        migrations.AddField(
            model_name='device',
            name='longitude',
            field=models.FloatField(blank=True, null=True, verbose_name='经度'),
        ),
        migrations.AddField(
            model_name='device',
            name='send_message',
            field=models.SmallIntegerField(choices=[(0, '是'), (1, '否')], default=1, verbose_name='信息提醒'),
        ),
        migrations.AddField(
            model_name='device',
            name='status',
            field=models.SmallIntegerField(choices=[(0, '新设备'), (1, '正常'), (2, '离线重登'), (3, '离线')], default=0, verbose_name='状态'),
        ),
    ]
