# Generated by Django 2.0.2 on 2018-05-10 08:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_auto_20180510_0303'),
    ]

    operations = [
        migrations.AddField(
            model_name='device',
            name='judge_date',
            field=models.DateTimeField(blank=True, null=True, verbose_name='监控时间'),
        ),
    ]
