# Generated by Django 2.0.2 on 2018-05-12 21:18

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_device_judge_date'),
    ]

    operations = [
        migrations.CreateModel(
            name='CheckLog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(blank=True, null=True, verbose_name='检测时间')),
                ('status', models.SmallIntegerField(choices=[(0, '在线'), (1, '离线')], default=0, verbose_name='状态')),
                ('device', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.Device', verbose_name='设备')),
            ],
            options={
                'verbose_name': '设备检测记录',
                'verbose_name_plural': '设备检测记录',
            },
        ),
        migrations.CreateModel(
            name='MessageLog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(blank=True, null=True, verbose_name='发送时间')),
                ('message', models.CharField(blank=True, max_length=64, null=True, verbose_name='信息')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='收信人')),
            ],
            options={
                'verbose_name': '信息记录',
                'verbose_name_plural': '信息记录',
            },
        ),
    ]
